/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package coffee.UI;

import coffee.DAO.NhanVienDAO;
import coffee.Entity.NhanVien;
import coffee.Utils.Auth;
import coffee.Utils.MsgBox;
import coffee.Utils.XImage;
import java.awt.Image;
import java.io.File;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Đặng Thành Trung
 */
public class NhanVienDialog extends javax.swing.JDialog {

    /**
     * Creates new form NhanVienDialog
     */
    public NhanVienDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        panDemo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdoQuanLi = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        txtMaNV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        txtHoTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        txtSDT = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        lblAnh = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnChonAnh = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnMucLuong = new javax.swing.JLabel();
        txtSoNgayLamViec = new javax.swing.JTextField();
        txtTienThuongThem = new javax.swing.JTextField();
        cboTienLuong = new javax.swing.JComboBox();
        txtTongTienLuong = new javax.swing.JTextField();
        btnTinhTien = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMK2 = new javax.swing.JPasswordField();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pan2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabs.setBackground(new java.awt.Color(204, 204, 255));
        tabs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        panDemo.setBackground(new java.awt.Color(255, 204, 204));
        panDemo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã Nhân Viên:");
        panDemo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 52, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mật khẩu:");
        panDemo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 102, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Họ Tên:");
        panDemo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 194, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Giới Tính:");
        panDemo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 254, -1, -1));

        rdoNam.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoNam.setText("Nam");
        panDemo.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 250, -1, -1));

        rdoNu.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoNu.setText("Nữ");
        panDemo.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 250, 71, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Vai Trò:");
        panDemo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 303, -1, -1));

        rdoQuanLi.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(rdoQuanLi);
        rdoQuanLi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoQuanLi.setText("Quản Lí");
        panDemo.add(rdoQuanLi, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 299, -1, -1));

        rdoNhanVien.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoNhanVien.setText("Nhân viên");
        panDemo.add(rdoNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 299, -1, -1));

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 49, 264, -1));

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 99, 264, -1));

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 191, 264, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Số Điện Thoại:");
        panDemo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 52, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Gmail:");
        panDemo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 102, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Lương:");
        panDemo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 148, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Địa Chỉ:");
        panDemo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 194, -1, -1));

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        panDemo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 200, 288, -1));

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 49, 288, -1));

        txtGmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 99, 288, -1));

        txtLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 145, 288, -1));

        lblAnh.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblAnh.setForeground(new java.awt.Color(255, 255, 255));
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        panDemo.add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 230, 287));

        btnThem.setBackground(new java.awt.Color(204, 204, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/them24.png"))); // NOI18N
        btnThem.setText("Thêm Nhân Viên");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        panDemo.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 550, 200, -1));

        btnSua.setBackground(new java.awt.Color(204, 204, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa Nhân Viên");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        panDemo.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 500, 200, -1));

        btnXoa.setBackground(new java.awt.Color(204, 204, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/xoa24.png"))); // NOI18N
        btnXoa.setText("Xóa Nhân Viên");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        panDemo.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 230, -1));

        btnLamMoi.setBackground(new java.awt.Color(204, 204, 255));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/moi24.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        panDemo.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 230, -1));

        btnChonAnh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/mâynh.jpg"))); // NOI18N
        btnChonAnh.setText("Chọn Ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });
        panDemo.add(btnChonAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 147, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Số ngày làm việc:");
        panDemo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 396, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Tiền Thưởng Thêm:");
        panDemo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 445, -1, -1));

        btnMucLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMucLuong.setText("Mức Lương:");
        panDemo.add(btnMucLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 491, -1, -1));

        txtSoNgayLamViec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtSoNgayLamViec, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 391, 197, 33));

        txtTienThuongThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtTienThuongThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 442, 197, -1));

        cboTienLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboTienLuong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100000", "200000", "300000", "400000" }));
        panDemo.add(cboTienLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 488, 197, -1));

        txtTongTienLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtTongTienLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 535, 197, -1));

        btnTinhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/maytinhtay.jpg"))); // NOI18N
        btnTinhTien.setText("Tính Tiền Lương");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });
        panDemo.add(btnTinhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 583, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Tổng Tiền Lương");
        panDemo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 538, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Xác Nhận Mật Khẩu:");
        panDemo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 148, -1, -1));

        txtMK2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panDemo.add(txtMK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 145, 264, -1));

        btnFirst.setBackground(new java.awt.Color(204, 204, 255));
        btnFirst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/Button-First-icon.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        panDemo.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        btnPrev.setBackground(new java.awt.Color(204, 204, 255));
        btnPrev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/Button-Rewind-icon.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        panDemo.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        btnLast.setBackground(new java.awt.Color(204, 204, 255));
        btnLast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/Button-Last-icon.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        panDemo.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        btnNext.setBackground(new java.awt.Color(204, 204, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/Button-Forward-icon.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        panDemo.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        tabs.addTab("Nhân Viên", new javax.swing.ImageIcon(getClass().getResource("/coffee/icon/nhanvien32.png")), panDemo); // NOI18N

        pan2.setBackground(new java.awt.Color(255, 204, 204));

        tblNhanVien.setBackground(new java.awt.Color(67, 221, 236));
        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaNV", "Tên Nhân Viên", "Giới Tính", "Vai Trò", "Địa Chỉ", "Số Điện Thoại", "Gmail", "Lương ", "Hình"
            }
        ));
        tblNhanVien.setRowHeight(22);
        tblNhanVien.setRowSelectionAllowed(false);
        tblNhanVien.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/icon/timkiem24.png"))); // NOI18N
        jLabel16.setText("Tìm Kiếm Nhân Viên Theo Tên:");

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Danh Sách", new javax.swing.ImageIcon(getClass().getResource("/coffee/icon/danhsach.png")), pan2); // NOI18N

        jPanel1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 670));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        chonAnh();
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        tinhTien();
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        First();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        Prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        Last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        Next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        tblNhanVien.setDefaultEditor(Object.class, null);
        if (evt.getClickCount() == 2) {
            this.row = tblNhanVien.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        timKiem();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhanVienDialog dialog = new NhanVienDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JLabel btnMucLuong;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboTienLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel panDemo;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLi;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JPasswordField txtMK2;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoNgayLamViec;
    private javax.swing.JTextField txtTienThuongThem;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTienLuong;
    // End of variables declaration//GEN-END:variables

    NhanVienDAO dao = new NhanVienDAO();
    int row = -1;
    NumberFormat formatter = new DecimalFormat("#.###");
    JFileChooser fileChooser = new JFileChooser();

    void init() {
        fillTable();
    }
    

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> list = dao.selectAll();
            for (NhanVien nv : list) {
                Object[] row
                        = {
                            nv.getMaNV(),
//                                                        nv.getMatKhau(),
                            nv.getHoTen(),
                            nv.isGioiTinh() ? "Nam" : "Nữ",
                            nv.isVaiTro() ? "Quản Lí" : "Nhân viên",
                            nv.getDiaChi(),
                            nv.getsDT(),
                            nv.getEmail(),
                            formatter.format(nv.getLuong()),
                            nv.getHinh(),};
                model.addRow(row);// thêm một hàng vào table
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    
    
    void chonAnh() {
        fileChooser = new JFileChooser("logos\\");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file);// lưu hình vào thư mục logos
//            ImageIcon icon = XImage.read(file.getName());// đọc hình từ logos

            ImageIcon image = new ImageIcon("" + XImage.read(file.getName()));
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);

            lblAnh.setToolTipText(file.getName());// giữ tên hình trong tooltip
        }
    }
    
    
    void edit() {
        String manv = (String) tblNhanVien.getValueAt(this.row, 0);
        NhanVien nv = dao.selectById(manv);
        this.setForm(nv);
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }
    
    void setForm1(NhanVien nv) {
        txtMaNV.setText(nv.getMaNV());
        txtMatKhau.setText(nv.getMatKhau());
        txtMK2.setText(nv.getMatKhau());
        txtHoTen.setText(nv.getHoTen());
        rdoNam.setSelected(nv.isGioiTinh());
        rdoNu.setSelected(!nv.isGioiTinh());
        rdoQuanLi.setSelected(nv.isVaiTro());
        rdoNhanVien.setSelected(!nv.isVaiTro());
        txtSDT.setText(nv.getsDT());
        txtGmail.setText(nv.getEmail());
        txtLuong.setText(String.valueOf(formatter.format(nv.getLuong())));
        txtDiaChi.setText(nv.getDiaChi());
    }
    
    
    void setForm (NhanVien nv) { 
        this.setForm1(nv);
        if (!nv.getHinh().equals("")) {
            lblAnh.setToolTipText(nv.getHinh());
            ImageIcon image = new ImageIcon("" + XImage.read(nv.getHinh()));
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);
        } else {
            lblAnh.setToolTipText(nv.getHinh());
            ImageIcon image = new ImageIcon("logos\\no-image-nv.png");
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);
        }
    }
    
    
    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setMatKhau(txtMatKhau.getText());
        nv.setHoTen(txtHoTen.getText());
        nv.setGioiTinh(rdoNam.isSelected());
        nv.setVaiTro(rdoQuanLi.isSelected());
        nv.setsDT(txtSDT.getText());
        nv.setEmail(txtGmail.getText());
        nv.setLuong(Double.parseDouble(txtLuong.getText().replaceAll(",", "")));
        nv.setDiaChi(txtDiaChi.getText());
        nv.setHinh(lblAnh.getToolTipText());
        return nv;
    }
    
    
    void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiem.getText();
            List<NhanVien> list = dao.selectByKeyword(keyword);
            for (NhanVien nv : list) {
                Object[] row
                        = {
                            nv.getMaNV(),
//                            nv.getMatKhau(),
                            nv.getHoTen(),
                            nv.isGioiTinh() ? "Nam" : "Nữ",
                            nv.isVaiTro() ? "Quản Lí" : "Nhân viên",
                            nv.getDiaChi(),
                            nv.getsDT(),
                            nv.getEmail(),
                            nv.getLuong(),
                            nv.getHinh(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    
    
    void Last() {
        this.row = tblNhanVien.getRowCount() - 1;
        this.edit();
    }

    
    void Next() {
        if (this.row < tblNhanVien.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    
    void First() {
        this.row = 0;
        this.edit();
    }
    

    void Prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }
    

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblNhanVien.getRowCount() - 1);
        txtMaNV.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    
    void clearForm() {
        NhanVien nv = new NhanVien();
        this.setForm1(nv);
        txtSoNgayLamViec.setText("");
        txtTienThuongThem.setText("");
        txtTongTienLuong.setText("");
        this.row = -1;
        this.updateStatus();
    }
    
    
    void tinhTien() {
        while (true) {
            if (txtSoNgayLamViec.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Số ngày làm việc không được bỏ trống ! ");
                return;
            } else if (!txtSoNgayLamViec.getText().trim().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ngày làm việc phải là số ! ");
                return;
            } else if (Double.parseDouble(txtSoNgayLamViec.getText().trim()) > 31) {
                JOptionPane.showMessageDialog(null, "Số ngày làm việc phải nhỏ hơn 31");
                return;
            } else {
                break;
            }
        }
        double ngay = Double.parseDouble(txtSoNgayLamViec.getText().trim());
        String a = (String) cboTienLuong.getSelectedItem();
        double LuongCB = Double.parseDouble(a.replaceAll(",", ""));
        double TienLuong;

        if (txtTienThuongThem.getText().trim().equals("")) {
            TienLuong = ngay * LuongCB;
        } else {
            while (true) {
                if (!txtTienThuongThem.getText().trim().matches("[0-9]+")) {
                    JOptionPane.showMessageDialog(null, "Tiền thưởng phải là số ! ");
                    return;
                } else if (Double.parseDouble(txtTienThuongThem.getText().trim()) > 500000) {
                    JOptionPane.showMessageDialog(null, "Tiền thưởng phải nhỏ hơn 500.000 ");
                    return;
                } else {
                    break;
                }
            }
            double Thuong = Double.parseDouble(txtTienThuongThem.getText().trim());
            TienLuong = (ngay * LuongCB) + Thuong;
        }
        txtTongTienLuong.setText(formatter.format(TienLuong) + " VNĐ");
    }
    
    
    void insert() {
//        if (vali_dateTEXT1() == true) {
            NhanVien nv = getForm();
            String mk2 = new String(txtMK2.getPassword());
            if (!mk2.equals(nv.getMatKhau())) {
                MsgBox.alert(this, "Mật khẩu không trùng khớp!");
            } else {
                try {
                    dao.insert(nv);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Thêm nhân viên thành công!");
                } catch (Exception e) {
                    System.out.println(e);
                    MsgBox.alert(this, "Thêm nhân viên thất bại!");
                }
            }
        }
//    }
    
    
    
     void update() {
//        if (vali_dateTEXT2() == true) {
            NhanVien nv = getForm();
            String mk2 = new String(txtMK2.getPassword());
            if (!mk2.equals(nv.getMatKhau())) {
                MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
            } else {
                try {
                    dao.update(nv);
                    fillTable();
                    MsgBox.alert(this, "Cập nhật thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Cập nhập thất bại!");
                }
            }
        }
//    }

     
     
    void delete() {
//        if (vali_dateTEXT2() == true) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xóa!");
            } else {
                String manv = txtMaNV.getText();
                if (manv.equals(Auth.user.getMaNV())) {
                    MsgBox.alert(this, "Bạn không được xóa chính bạn!");
                } else if (MsgBox.confirm(this, "Bạn thật sự muốn xóa nhân viên này!")) {
                    try {
                        dao.delete(manv);
                        this.fillTable();
                        this.clearForm();
                        MsgBox.alert(this, "Xóa thành công!");
                    } catch (Exception e) {
                        MsgBox.alert(this, "Xóa thất bại!");
                    }
                }
            }
        }
//    }
    
    
}
