/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package coffee.UI;

/**
 *
 * @author Đặng Thành Trung
 */
public class ThongKeDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThongKeDialog
     */
    public ThongKeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabs2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTopSP2 = new javax.swing.JTable();
        btnXuatBC3 = new javax.swing.JButton();
        rdoNgayHomNay2 = new javax.swing.JRadioButton();
        rdo1Thang2 = new javax.swing.JRadioButton();
        rdo3Thang2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        btnXuatBC4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTongDoanhThu = new javax.swing.JLabel();
        lblTongDoanhThu1 = new javax.swing.JLabel();
        chkTheoNgay = new javax.swing.JCheckBox();
        txtNgayThem = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabs2.setBackground(new java.awt.Color(255, 204, 204));
        tabs2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        tabs2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabs2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tblTopSP2.setAutoCreateRowSorter(true);
        tblTopSP2.setBackground(new java.awt.Color(67, 221, 236));
        tblTopSP2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblTopSP2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ SP", "TÊN SP", "ĐÃ BÁN"
            }
        ));
        tblTopSP2.setRowHeight(22);
        jScrollPane4.setViewportView(tblTopSP2);

        btnXuatBC3.setBackground(new java.awt.Color(0, 255, 102));
        btnXuatBC3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXuatBC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/excel24.png"))); // NOI18N
        btnXuatBC3.setText("Xuất báo cáo");
        btnXuatBC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBC3ActionPerformed(evt);
            }
        });

        rdoNgayHomNay2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoNgayHomNay2);
        rdoNgayHomNay2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNgayHomNay2.setSelected(true);
        rdoNgayHomNay2.setText("Ngày hôm nay");
        rdoNgayHomNay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNgayHomNay2ActionPerformed(evt);
            }
        });

        rdo1Thang2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdo1Thang2);
        rdo1Thang2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdo1Thang2.setText("1 tháng vừa qua");
        rdo1Thang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo1Thang2ActionPerformed(evt);
            }
        });

        rdo3Thang2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdo3Thang2);
        rdo3Thang2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdo3Thang2.setText("3 tháng vừa qua");
        rdo3Thang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo3Thang2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXuatBC3)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(rdoNgayHomNay2)
                .addGap(18, 18, 18)
                .addComponent(rdo1Thang2)
                .addGap(18, 18, 18)
                .addComponent(rdo3Thang2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNgayHomNay2)
                    .addComponent(rdo1Thang2)
                    .addComponent(rdo3Thang2))
                .addGap(79, 79, 79)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnXuatBC3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs2.addTab("TOP SẢN PHẨM", new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/iconThongKeSP.png")), jPanel1); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        tblDoanhThu.setBackground(new java.awt.Color(67, 221, 236));
        tblDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NGÀY", "DOANH THU"
            }
        ));
        tblDoanhThu.setRowHeight(22);
        jScrollPane5.setViewportView(tblDoanhThu);

        btnXuatBC4.setBackground(new java.awt.Color(0, 255, 102));
        btnXuatBC4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXuatBC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee/iicon/excel24.png"))); // NOI18N
        btnXuatBC4.setText("Xuất báo cáo");
        btnXuatBC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBC4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tổng doanh thu:");

        lblTongDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTongDoanhThu.setForeground(new java.awt.Color(153, 0, 51));
        lblTongDoanhThu.setText("jLabel2");

        lblTongDoanhThu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTongDoanhThu1.setForeground(new java.awt.Color(153, 0, 51));
        lblTongDoanhThu1.setText("VNĐ");

        chkTheoNgay.setBackground(new java.awt.Color(204, 204, 255));
        chkTheoNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkTheoNgay.setText("Theo ngày:");
        chkTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTheoNgayActionPerformed(evt);
            }
        });

        txtNgayThem.setBackground(new java.awt.Color(204, 204, 255));
        txtNgayThem.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(chkTheoNgay)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongDoanhThu)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongDoanhThu1)))
                .addContainerGap(440, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXuatBC4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkTheoNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTongDoanhThu)
                    .addComponent(lblTongDoanhThu1))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatBC4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabs2.addTab("DOANH THU", new javax.swing.ImageIcon(getClass().getResource("/coffee/icon/doanhthu24.png")), jPanel4); // NOI18N

        getContentPane().add(tabs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, 530));

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thống Kê");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 898, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatBC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBC3ActionPerformed
    }//GEN-LAST:event_btnXuatBC3ActionPerformed

    private void rdoNgayHomNay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNgayHomNay2ActionPerformed
    }//GEN-LAST:event_rdoNgayHomNay2ActionPerformed

    private void rdo1Thang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo1Thang2ActionPerformed
    }//GEN-LAST:event_rdo1Thang2ActionPerformed

    private void rdo3Thang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo3Thang2ActionPerformed
    }//GEN-LAST:event_rdo3Thang2ActionPerformed

    private void btnXuatBC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBC4ActionPerformed
    }//GEN-LAST:event_btnXuatBC4ActionPerformed

    private void chkTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTheoNgayActionPerformed
    }//GEN-LAST:event_chkTheoNgayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongKeDialog dialog = new ThongKeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatBC3;
    private javax.swing.JButton btnXuatBC4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkTheoNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTongDoanhThu;
    private javax.swing.JLabel lblTongDoanhThu1;
    private javax.swing.JRadioButton rdo1Thang2;
    private javax.swing.JRadioButton rdo3Thang2;
    private javax.swing.JRadioButton rdoNgayHomNay2;
    private javax.swing.JTabbedPane tabs2;
    private javax.swing.JTable tblDoanhThu;
    private javax.swing.JTable tblTopSP2;
    private com.toedter.calendar.JDateChooser txtNgayThem;
    // End of variables declaration//GEN-END:variables
}
